let
  nate = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID1w4OTAaFlD4l9GSZUbYUdSVFSW0CYd3o5r00Ra3UBT nathan@bodie.dev";

  # VPS host key. Generated by dev-vps/deploy.sh hostkey BEFORE the machine
  # exists, and installed onto it during the nixos-anywhere run via
  # --extra-files, so the host can decrypt secrets at boot without your laptop
  # present. Private half lives only in dev-vps/.host-keys/ (gitignored).
  vps = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF9LOIhKmwO7PacG6XHT4ujg3o4JZQSWDKyNE7GnXDbP root@vps";
in {
  "secrets/tailscale-authkey.age".publicKeys = [ nate vps ];
}
